apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: http
    - name: "51413"
      port: 51413
      targetPort: peer-tcp
    - name: 51413-udp
      port: 51413
      protocol: UDP
      targetPort: peer-udp
